version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::038462753284:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-2bqcJiZkbRMl"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::038462753284:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-kjUnsYW3lwU5"
cloudformation_execution_role = "arn:aws:iam::038462753284:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-49OvZBvH2N7s"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-rqd3axx84w38"
image_repository = ""
region = "us-east-1"
